from tkinter import*
test = Tk()
test.title("패션지오_Picking cell")
test.geometry('1200x900')
label_1 = Label(test, text = "시작셀 12-00-00-00",font = ("맑은고딕" ,25),fg= "blue")
label_1.place (x = 27,y = 20)
label_2 = Label(test, text = "종료",font = ("맑은고딕" ,25),fg= "black")
label_2.place (x = 360,y = 20)
label_3 = Label(test, text = "Picking  Cell :                1-123",font = ("Adobe 고딕 Std B" ,25),fg= "black")
label_3.place (x = 30,y = 80)
label_4 = Label(test, text = "Location :        12-0D-RU-07",font = ("Adobe 고딕 Std B" ,25),fg= "black")
label_4.place (x = 30,y = 140)
label_5 = Label(test, text = "TWWSTL72040MT55   [  1 ]",font = ("Adobe 고딕 Std B" ,25),fg= "red",bg="yellow")
label_5.place (x = 30,y = 200)
label_6 = Label(test, text = "[이전]        [피킹 x]        [다음]",font = ("Adobe 고딕 Std B" ,25),fg= "red")
label_6.place (x = 30,y = 260)
photo_7 = PhotoImage(file = "sapimg3.PNG")
label_7 = Label(test, image= photo_7)
label_7.place (x = 600,y = 20)
test.mainloop()
